name: Release on Tag

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka

      - name: Build binary
        run: nuitka --onefile --output-filename=iiidmformatter.exe ./src/main.py

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/iiidmformatter
          name: Release ${{ github.ref_name }}
          body: |
            See the [changelog](https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}) for details.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
